### ISSUE TITLE
Will need to be updated for GNOME 45

### ISSUE THREAD

**Issue by elcste** [akiirui/hide-universal-access#3]
All extensions will need to be updated for GNOME 45: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

I don't really know js but I might give it a try, but I'm busy for the next couple weeks.

Ubuntu mantic, the release under development, has updated to GNOME Shell 45 beta so can be used to try.

**Comment by akiirui** [comment]
Thanks for the reminder, I will update the extension after GNOME 45 is released.

**Comment by akiirui** [comment]
I've tried upgrading it to GNOME 45 (https://github.com/akiirui/hide-universal-access/commit/4d26912949cc53060408d94828e224abd875be58) but don't have an environment to test it.
It should work. Feedback is welcome, thanks.

**Comment by elcste** [comment]
I tried manually installing the zip file, both the 45 tag and git master, and I'm seeing the error `import not found: default`.

I am testing using Ubuntu mantic, with GNOME Shell package version `45~beta.1-0ubuntu2`.

**Comment by akiirui** [comment]
Well, maybe we're missing curly braces...

**Comment by akiirui** [comment]
Please try https://github.com/akiirui/hide-universal-access/commit/4d5b6a448cd7602370743311752c845028e46afe thanks.

**Comment by elcste** [comment]
That one works 😀 

Thanks again!
