### ISSUE TITLE
PC DOESN'T SHUT DOWN PROPERLY

### ISSUE THREAD

**Issue by Tony592** [akiirui/hide-universal-access#4]
I've been having a strange behaviour with this extension since May 2024, sometimes (more or less two three times at day) after shutting down the pc remains with the fan on and I have to hold the power button to shut it down properly.
I have this behaviour on different kernels and different distributions with gnome 45 and gnome 46.
I have tried with and without nvidia gpu, I have also tried updating BIOS without luck.
When the extension is disabled the problem disappear.

**Comment by akiirui** [comment]
Are you sure this issue caused by this extension?
Please show me the journal of the unsuccessful shutdown.

**Comment by Tony592** [comment]
![journal](https://github.com/user-attachments/assets/b14a6bc0-0aee-404f-af35-6b123962ba24)

Here there is a journal, I checked but did not show anything wrong, I'm pretty sure is 
this extension because after removing that the problem is gone. I have other third party extensions enabled and I don't have any problem with those.
I have this problem only in a desktop machine, laptop is whit same OS and gnome version is not affected.

**Comment by akiirui** [comment]
Please paste the full log to any pastebin or upload a file.
But it looks like your system was successfully shut down, And I can't reproduce it.

**Comment by Tony592** [comment]
If you want I can try to riproduce the problem reanable the extension, but as you said, in the journal seems that the machine il properly Power off. Only cpu, case fan and gpu remains on. Maybe some particular driver in the machine that have some conflict with the extension. For completness the bug Is similar to this one https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2059738 and disappear when the extension is turned off.

**Comment by akiirui** [comment]
So, where is your log file? The screenshot above gives too little information.

This extension is a very simple script, and it shouldn't affect anything at the system level.
I think this is a hardware/kernel/driver issue. Because it only happens on your PC.
If you don't provide the full log, I can only suggest you try to update the BIOS, kernel and drivers.

**Comment by Tony592** [comment]
I will provide the full log If the problem occurs again. I just tried to update: driver, kernel and Bios without luck, now i update also the SO, I'm using fedora 41 with gnome 47 now, maybe this can solve the problem.

**Comment by Tony592** [comment]
UPDATE:

I tried several power off and everything goes fine after updating Fedora 41 with Gnome 47. Maybe was some issue related to previous gnome version or some drivers.

**Comment by akiirui** [comment]
Okay, reopen it if you meet this issue again.
